title: Association of Bioinformatics Professionals
email: info@bioinfopro.org
description: >-
  A minimal, fast Jekyll template configured for GitHub pages with custom branding.
baseurl: "" 
url: "" 
markdown: kramdown
